#!/usr/bin/env bash
# ============================================================================
# check-generated-content-is-verifiable.sh
#
# Generated content is the only lever that reaches a zero storage multiplier,
# and it is safe for exactly one reason: `manifest_id` is the hash of the
# bytes, so a node can run the description, hash the output and compare.
#
# That reason stops holding the moment any of three things drift:
#
#   1. a generator uses floating point, so two machines can produce different
#      bytes and disagree about whether an object is valid, which is a fork;
#   2. the verify path stops comparing against the id, so a spec could be
#      paired with an id it does not derive and readers would be handed the
#      wrong object under an id they trust;
#   3. a generator runs without a metered budget, so thirty-two bytes of
#      upload can burn unbounded reader CPU.
#
# Each is invisible in review and fatal in production, so each is checked
# here rather than left to a reader noticing.
#
# Usage:
#   bash scripts/check-generated-content-is-verifiable.sh              # gate
#   bash scripts/check-generated-content-is-verifiable.sh --self-test  # canary
# ============================================================================
set -euo pipefail

ROOT="${BUDLUM_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
TARGET="$ROOT/src/storage/generated.rs"

fail() { echo "FAIL: $*" >&2; exit 1; }

# --- the three checks, as functions so the canaries can drive them ---------

# 1. No floating point in the generator module.
#
# Matches the type names and the literal form. Comments and doc text are
# stripped first, because this file's own documentation explains *why* floats
# are refused and must not trip the check that refuses them.
find_floats() {
  local file="$1"
  sed -e 's://.*::' "$file" \
    | grep -nE '\b(f32|f64)\b|\bas +f(32|64)\b|[0-9]+\.[0-9]+f(32|64)?' \
    || true
}

# 2. The verify path compares generated bytes against the expected id.
find_id_check() {
  local file="$1"
  # `generate_and_verify` has to hash its output and compare to the argument.
  awk '/fn generate_and_verify/,/^}/' "$file" \
    | grep -cE 'ContentId::of|IdMismatch' \
    || true
}

# 3. Every generator threads the meter rather than looping unmetered.
find_unmetered() {
  local file="$1"
  # Every `fn draw_*` must take a Meter and charge at least once.
  local missing=""
  while IFS= read -r fn; do
    local name="${fn%%(*}"
    name="${name##*fn }"
    local body
    body="$(awk -v f="fn ${name}" 'index($0,f){flag=1} flag{print} flag&&/^}/{exit}' "$file")"
    if ! printf '%s' "$body" | grep -q 'meter.charge'; then
      missing="${missing}${name} "
    fi
  done < <(grep -oE 'fn draw_[a-z_]+\(' "$file" || true)
  printf '%s' "$missing"
}

# --------------------------------------------------------------- self test
if [ "${1:-}" = "--self-test" ]; then
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  canaries=0

  # Canary 1: an f64 in a generator is caught.
  cat > "$tmp/c1.rs" <<'EOF'
fn draw_thing(meter: &mut Meter) -> Vec<u8> {
    let t: f64 = 0.5;
    meter.charge(1)?;
    vec![t as u8]
}
EOF
  [ -n "$(find_floats "$tmp/c1.rs")" ] || fail "canary 1: an f64 in a generator was not detected"
  canaries=$((canaries + 1))

  # Canary 2: an `as f32` cast is caught.
  cat > "$tmp/c2.rs" <<'EOF'
fn draw_thing(meter: &mut Meter) -> Vec<u8> {
    let x = 3 as f32;
    meter.charge(1)?;
    vec![x as u8]
}
EOF
  [ -n "$(find_floats "$tmp/c2.rs")" ] || fail "canary 2: an 'as f32' cast was not detected"
  canaries=$((canaries + 1))

  # Canary 3: prose about floats must NOT be flagged, or this file's own
  # documentation would fail the gate it defines. This is the false positive
  # that would make the check unusable.
  cat > "$tmp/c3.rs" <<'EOF'
// Floating point is refused here: f64 differs between machines.
/// Uses fixed point rather than f32, on purpose.
fn draw_thing(meter: &mut Meter) -> Vec<u8> {
    meter.charge(1)?;
    vec![0u8]
}
EOF
  [ -z "$(find_floats "$tmp/c3.rs")" ] || fail "canary 3: prose naming f32/f64 must not be flagged"
  canaries=$((canaries + 1))

  # Canary 4: a verify path that does not compare the id is caught.
  cat > "$tmp/c4.rs" <<'EOF'
pub fn generate_and_verify(spec: &S, expected: ContentId) -> Result<Vec<u8>, E> {
    let bytes = generate(spec)?;
    Ok(bytes)
}
EOF
  [ "$(find_id_check "$tmp/c4.rs")" = "0" ] \
    || fail "canary 4: a verify path with no id comparison was not detected"
  canaries=$((canaries + 1))

  # Canary 5: a verify path that does compare must pass, so the gate is not
  # rejecting everything.
  cat > "$tmp/c5.rs" <<'EOF'
pub fn generate_and_verify(spec: &S, expected: ContentId) -> Result<Vec<u8>, E> {
    let bytes = generate(spec)?;
    let produced = ContentId::of(&bytes);
    if produced != expected { return Err(GenerateError::IdMismatch { expected, produced }); }
    Ok(bytes)
}
EOF
  [ "$(find_id_check "$tmp/c5.rs")" != "0" ] \
    || fail "canary 5: an honest verify path must pass"
  canaries=$((canaries + 1))

  # Canary 6: a generator that never charges the meter is caught.
  cat > "$tmp/c6.rs" <<'EOF'
fn draw_leak(seed: &[u8; 32], len: u32, meter: &mut Meter) -> Vec<u8> {
    let mut out = Vec::new();
    for _ in 0..len { out.push(0u8); }
    out
}
EOF
  [ -n "$(find_unmetered "$tmp/c6.rs")" ] \
    || fail "canary 6: an unmetered generator loop was not detected"
  canaries=$((canaries + 1))

  # Canary 7: a metered generator must pass.
  cat > "$tmp/c7.rs" <<'EOF'
fn draw_ok(seed: &[u8; 32], len: u32, meter: &mut Meter) -> Vec<u8> {
    let mut out = Vec::new();
    for _ in 0..len { meter.charge(1)?; out.push(0u8); }
    out
}
EOF
  [ -z "$(find_unmetered "$tmp/c7.rs")" ] \
    || fail "canary 7: a metered generator must not be flagged"
  canaries=$((canaries + 1))

  # Canary 8: a clean file produces no findings at all, so none of the three
  # checks is passing by matching everything.
  cat > "$tmp/c8.rs" <<'EOF'
fn helper(x: i64) -> i64 { x + 1 }
EOF
  [ -z "$(find_floats "$tmp/c8.rs")" ] || fail "canary 8: a clean file must not be flagged"
  [ -z "$(find_unmetered "$tmp/c8.rs")" ] || fail "canary 8: a file with no generators is clean"
  canaries=$((canaries + 1))

  echo "generated content gate self-test OK: $canaries canaries"
  exit 0
fi

# ------------------------------------------------------------------- gate
[ -f "$TARGET" ] || fail "missing $TARGET"

floats="$(find_floats "$TARGET")"
if [ -n "$floats" ]; then
  echo "$floats" >&2
  fail "floating point in a generator: two machines can disagree, which forks the chain"
fi

if [ "$(find_id_check "$TARGET")" = "0" ]; then
  fail "generate_and_verify does not compare the output against the expected id"
fi

unmetered="$(find_unmetered "$TARGET")"
if [ -n "$unmetered" ]; then
  fail "generator(s) run without charging the meter: $unmetered"
fi

echo "OK: generators are integer-only, id-verified and metered"
